// src/app/sitemap.ts — Dynamic sitemap with blog posts from Supabase
import { MetadataRoute } from 'next';
import { getPublishedPosts, getAllPublishedSlugs } from '@/lib/blog';

const BASE_URL = 'https://www.shepherdaitech.com';

// ── Church SEO URLs — hardcoded for Vercel build ──────────────────────────
const CHURCH_SEO_URLS: MetadataRoute.Sitemap = [
  { url: `${BASE_URL}/find-church/tx/houston/baptist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/houston/methodist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/houston/lutheran`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/houston/presbyterian`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/houston/pentecostal`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/houston/catholic`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/houston/non-denominational`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/houston/anglican`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/houston/orthodox`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/houston/adventist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/houston/reformed`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/houston/nazarene`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/houston/assembly-of-god`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/dallas/baptist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/dallas/methodist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/dallas/lutheran`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/dallas/presbyterian`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/dallas/pentecostal`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/dallas/catholic`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/dallas/non-denominational`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/dallas/anglican`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/dallas/orthodox`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/dallas/adventist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/dallas/reformed`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/dallas/nazarene`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/dallas/assembly-of-god`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/austin/baptist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/austin/methodist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/austin/lutheran`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/austin/presbyterian`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/austin/pentecostal`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/austin/catholic`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/austin/non-denominational`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/austin/anglican`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/austin/orthodox`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/austin/adventist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/austin/reformed`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/austin/nazarene`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/austin/assembly-of-god`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/san-antonio/baptist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/san-antonio/methodist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/san-antonio/lutheran`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/san-antonio/presbyterian`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/san-antonio/pentecostal`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/san-antonio/catholic`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/san-antonio/non-denominational`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/san-antonio/anglican`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/san-antonio/orthodox`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/san-antonio/adventist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/san-antonio/reformed`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/san-antonio/nazarene`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tx/san-antonio/assembly-of-god`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ny/new-york/baptist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ny/new-york/methodist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ny/new-york/lutheran`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ny/new-york/presbyterian`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ny/new-york/pentecostal`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ny/new-york/catholic`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ny/new-york/non-denominational`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ny/new-york/anglican`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ny/new-york/orthodox`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ny/new-york/adventist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ny/new-york/reformed`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ny/new-york/nazarene`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ny/new-york/assembly-of-god`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/los-angeles/baptist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/los-angeles/methodist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/los-angeles/lutheran`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/los-angeles/presbyterian`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/los-angeles/pentecostal`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/los-angeles/catholic`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/los-angeles/non-denominational`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/los-angeles/anglican`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/los-angeles/orthodox`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/los-angeles/adventist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/los-angeles/reformed`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/los-angeles/nazarene`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/los-angeles/assembly-of-god`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/il/chicago/baptist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/il/chicago/methodist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/il/chicago/lutheran`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/il/chicago/presbyterian`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/il/chicago/pentecostal`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/il/chicago/catholic`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/il/chicago/non-denominational`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/il/chicago/anglican`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/il/chicago/orthodox`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/il/chicago/adventist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/il/chicago/reformed`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/il/chicago/nazarene`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/il/chicago/assembly-of-god`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/az/phoenix/baptist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/az/phoenix/methodist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/az/phoenix/lutheran`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/az/phoenix/presbyterian`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/az/phoenix/pentecostal`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/az/phoenix/catholic`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/az/phoenix/non-denominational`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/az/phoenix/anglican`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/az/phoenix/orthodox`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/az/phoenix/adventist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/az/phoenix/reformed`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/az/phoenix/nazarene`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/az/phoenix/assembly-of-god`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/pa/philadelphia/baptist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/pa/philadelphia/methodist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/pa/philadelphia/lutheran`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/pa/philadelphia/presbyterian`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/pa/philadelphia/pentecostal`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/pa/philadelphia/catholic`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/pa/philadelphia/non-denominational`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/pa/philadelphia/anglican`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/pa/philadelphia/orthodox`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/pa/philadelphia/adventist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/pa/philadelphia/reformed`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/pa/philadelphia/nazarene`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/pa/philadelphia/assembly-of-god`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/san-diego/baptist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/san-diego/methodist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/san-diego/lutheran`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/san-diego/presbyterian`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/san-diego/pentecostal`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/san-diego/catholic`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/san-diego/non-denominational`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/san-diego/anglican`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/san-diego/orthodox`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/san-diego/adventist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/san-diego/reformed`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/san-diego/nazarene`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/san-diego/assembly-of-god`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/san-francisco/baptist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/san-francisco/methodist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/san-francisco/lutheran`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/san-francisco/presbyterian`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/san-francisco/pentecostal`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/san-francisco/catholic`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/san-francisco/non-denominational`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/san-francisco/anglican`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/san-francisco/orthodox`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/san-francisco/adventist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/san-francisco/reformed`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/san-francisco/nazarene`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ca/san-francisco/assembly-of-god`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/wa/seattle/baptist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/wa/seattle/methodist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/wa/seattle/lutheran`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/wa/seattle/presbyterian`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/wa/seattle/pentecostal`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/wa/seattle/catholic`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/wa/seattle/non-denominational`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/wa/seattle/anglican`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/wa/seattle/orthodox`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/wa/seattle/adventist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/wa/seattle/reformed`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/wa/seattle/nazarene`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/wa/seattle/assembly-of-god`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/co/denver/baptist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/co/denver/methodist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/co/denver/lutheran`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/co/denver/presbyterian`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/co/denver/pentecostal`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/co/denver/catholic`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/co/denver/non-denominational`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/co/denver/anglican`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/co/denver/orthodox`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/co/denver/adventist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/co/denver/reformed`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/co/denver/nazarene`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/co/denver/assembly-of-god`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tn/nashville/baptist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tn/nashville/methodist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tn/nashville/lutheran`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tn/nashville/presbyterian`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tn/nashville/pentecostal`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tn/nashville/catholic`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tn/nashville/non-denominational`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tn/nashville/anglican`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tn/nashville/orthodox`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tn/nashville/adventist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tn/nashville/reformed`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tn/nashville/nazarene`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/tn/nashville/assembly-of-god`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ga/atlanta/baptist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ga/atlanta/methodist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ga/atlanta/lutheran`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ga/atlanta/presbyterian`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ga/atlanta/pentecostal`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ga/atlanta/catholic`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ga/atlanta/non-denominational`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ga/atlanta/anglican`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ga/atlanta/orthodox`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ga/atlanta/adventist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ga/atlanta/reformed`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ga/atlanta/nazarene`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ga/atlanta/assembly-of-god`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/miami/baptist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/miami/methodist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/miami/lutheran`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/miami/presbyterian`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/miami/pentecostal`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/miami/catholic`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/miami/non-denominational`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/miami/anglican`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/miami/orthodox`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/miami/adventist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/miami/reformed`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/miami/nazarene`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/miami/assembly-of-god`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/orlando/baptist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/orlando/methodist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/orlando/lutheran`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/orlando/presbyterian`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/orlando/pentecostal`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/orlando/catholic`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/orlando/non-denominational`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/orlando/anglican`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/orlando/orthodox`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/orlando/adventist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/orlando/reformed`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/orlando/nazarene`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/orlando/assembly-of-god`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/nc/charlotte/baptist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/nc/charlotte/methodist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/nc/charlotte/lutheran`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/nc/charlotte/presbyterian`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/nc/charlotte/pentecostal`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/nc/charlotte/catholic`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/nc/charlotte/non-denominational`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/nc/charlotte/anglican`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/nc/charlotte/orthodox`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/nc/charlotte/adventist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/nc/charlotte/reformed`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/nc/charlotte/nazarene`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/nc/charlotte/assembly-of-god`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/in/indianapolis/baptist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/in/indianapolis/methodist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/in/indianapolis/lutheran`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/in/indianapolis/presbyterian`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/in/indianapolis/pentecostal`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/in/indianapolis/catholic`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/in/indianapolis/non-denominational`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/in/indianapolis/anglican`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/in/indianapolis/orthodox`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/in/indianapolis/adventist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/in/indianapolis/reformed`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/in/indianapolis/nazarene`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/in/indianapolis/assembly-of-god`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/oh/columbus/baptist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/oh/columbus/methodist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/oh/columbus/lutheran`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/oh/columbus/presbyterian`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/oh/columbus/pentecostal`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/oh/columbus/catholic`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/oh/columbus/non-denominational`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/oh/columbus/anglican`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/oh/columbus/orthodox`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/oh/columbus/adventist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/oh/columbus/reformed`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/oh/columbus/nazarene`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/oh/columbus/assembly-of-god`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/jacksonville/baptist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/jacksonville/methodist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/jacksonville/lutheran`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/jacksonville/presbyterian`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/jacksonville/pentecostal`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/jacksonville/catholic`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/jacksonville/non-denominational`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/jacksonville/anglican`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/jacksonville/orthodox`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/jacksonville/adventist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/jacksonville/reformed`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/jacksonville/nazarene`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/fl/jacksonville/assembly-of-god`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ma/boston/baptist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ma/boston/methodist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ma/boston/lutheran`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ma/boston/presbyterian`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ma/boston/pentecostal`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ma/boston/catholic`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ma/boston/non-denominational`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ma/boston/anglican`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ma/boston/orthodox`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ma/boston/adventist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ma/boston/reformed`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ma/boston/nazarene`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/ma/boston/assembly-of-god`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/mi/detroit/baptist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/mi/detroit/methodist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/mi/detroit/lutheran`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/mi/detroit/presbyterian`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/mi/detroit/pentecostal`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/mi/detroit/catholic`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/mi/detroit/non-denominational`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/mi/detroit/anglican`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/mi/detroit/orthodox`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/mi/detroit/adventist`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/mi/detroit/reformed`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/mi/detroit/nazarene`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
  { url: `${BASE_URL}/find-church/mi/detroit/assembly-of-god`, lastModified: new Date('2026-06-16'), changeFrequency: 'monthly' as const, priority: 0.6 },
];

// ── Static page URLs ────────────────────────────────────────────────────────
const STATIC_URLS: MetadataRoute.Sitemap = [
  { url: BASE_URL, lastModified: new Date(), changeFrequency: 'weekly', priority: 1.0 },
  { url: `${BASE_URL}/features`, lastModified: new Date('2026-06-18'), changeFrequency: 'weekly', priority: 0.9 },
  { url: `${BASE_URL}/pricing`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.9 },
  { url: `${BASE_URL}/blog`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.8 },
  { url: `${BASE_URL}/pt/blog`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.7 },
  { url: `${BASE_URL}/about`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5 },
  { url: `${BASE_URL}/contact`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5 },
  { url: `${BASE_URL}/faq`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5 },
  { url: `${BASE_URL}/privacy`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.3 },
  { url: `${BASE_URL}/terms`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.3 },
  { url: `${BASE_URL}/for-churches`, lastModified: new Date('2026-06-18'), changeFrequency: 'monthly', priority: 0.7 },
  { url: `${BASE_URL}/donation-management`, lastModified: new Date('2026-06-18'), changeFrequency: 'monthly', priority: 0.7 },
  { url: `${BASE_URL}/membership-management`, lastModified: new Date('2026-06-18'), changeFrequency: 'monthly', priority: 0.7 },
  { url: `${BASE_URL}/free-resources`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.7 },
  { url: `${BASE_URL}/free-tools`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.7 },
];

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  // ── Dynamically fetch blog post URLs from Supabase ──────────────────────
  let blogUrls: MetadataRoute.Sitemap = [];
  try {
    const enPosts = await getPublishedPosts('en');
    for (const post of enPosts) {
      blogUrls.push({
        url: `${BASE_URL}/blog/${post.slug}`,
        lastModified: post.published_at ? new Date(post.published_at) : new Date(post.created_at),
        changeFrequency: 'monthly' as const,
        priority: 0.7,
      });
    }
  } catch (err) {
    console.warn('sitemap: Failed to fetch EN blog posts, skipping dynamic URLs', err);
  }
  
  try {
    const ptPosts = await getPublishedPosts('pt-br');
    for (const post of ptPosts) {
      blogUrls.push({
        url: `${BASE_URL}/pt/blog/${post.slug}`,
        lastModified: post.published_at ? new Date(post.published_at) : new Date(post.created_at),
        changeFrequency: 'monthly' as const,
        priority: 0.6,
      });
    }
  } catch (err) {
    console.warn('sitemap: Failed to fetch PT blog posts, skipping dynamic URLs', err);
  }

  return [...STATIC_URLS, ...CHURCH_SEO_URLS, ...blogUrls];
}
